console.log( 1 + 1 );

try {
    hola();
} catch (error) {
    console.log('Error desde el catch...')
}

console.log( 2 + 2 );